### ISSUE TITLE
Some Error when import uncalled4

### ISSUE THREAD

**Issue by hpy17** [skovaka/uncalled4#1]
Hi Sam,

I have installed uncalled4 successfully and trying the below codes:
`from uncalled4 import PoreModel, Config, EventDetector, SignalProcessor

But it seems that there are still some problems, maybe tblib is forgotten to be installed. After tblib is installed, it would be successful.

And Also may I know what is the meaning of  two parameters '.PRMS_450BPS' and'.PRMS_70BPS'
`from uncalled4 import PoreModel, Config, EventDetector, SignalProcessor
m = PoreModel("dna_r9.4.1_400bps_6mer") #or "dna_r10.4.1_400bps_9mer", "rna_r9.4.1_70bps_5mer", custom TSV file
c = Config()
c.event_detector = EventDetector.PRMS_450BPS #or EventDetector.PRMS_70BPS
sp = SignalProcessor(m,c)
read = sp.process_signal(signal, normalize=True) #signal should be numpy array/list of un-normalized raw sample values

print(read.events["mean"])    #event current means
print(read.events["stdv"])    #event current stdvs
print(read.events["start"])   #event sample starts
print(read.events["length"])  #event sample lengths
print(read.signal)            #normalized raw signal (using method-of-moments)`

**Comment by hpy17** [comment]
And also when I'm trying the tool for event detector, it seems there are some other problems for kernel.
My numpy signal is like `[547 464 463 467 464 487 502 482 485 492 486 487 501 491 488 486 489 501
 481 491 494 489 502 496 494 494 495 491 500 497 485 492 502 483 509 494
 505 495 485 496 497 502 491 490 507 495 488 488 492 492 501 492 496 495
 484 482 487 482 491 490 497 512 495 486 490 493 493 486 491 492 502 499
 504 479 488 497 497 500 498 502 494 503 499 506 502 506 489 500 491 509
 508 487 491 475 490 491 479 493 499 501]`
And the code for this part is:

m = PoreModel("dna_r9.4.1_400bps_6mer") #or "dna_r10.4.1_400bps_9mer", "rna_r9.4.1_70bps_5mer", custom TSV file 
c = Config()
c.event_detector = EventDetector.PRMS_450BPS #or EventDetector.PRMS_70BPS
sp = SignalProcessor(m,c)
read = sp.process_signal(numpy_signal, normalize=True) #signal should be numpy array/list of un-normalized raw sample values
print(read.events["mean"])    #event current means
print(read.events["stdv"])    #event current stdvs
print(read.events["start"])   #event sample starts
print(read.events["length"])  #event sample length
print(read.signal)            #normalized raw signal (using method-of-moments)


But it still have some problems the kernel would die.
`Segmentation fault (core dumped)
`

**Comment by skovaka** [comment]
Thank you for trying this, I will add the tblib dependency. Are you able to run the example commands under the `example/` directory (first run `./download.sh`, then `./run.sh`)? Just wondering if it's an issue with that code snippet or if it's more fundamental. If the example script works, try turning your signal into a float array like this: `signal = np.array(signal, dtype=float)`. If that doesn't work, could you add `print(...)` statements between each line to see where the error happens? Segmentation faults in python can be difficult to debug.

The PRMS_450BPS is a preset set of event detection parameters for sequencing speeds of ~400-450 bases per second. These parameters control the event detector t-test window lengths and thresholds (specifically 'peak_height', 'threshold1', 'threshold2', 'window_length1', 'window_length2' via `dir(c.event_detector)`), which are set based on the expected number of samples-per-second and the observed signal alignment stay/skip rate when using those parameters.

**Comment by hpy17** [comment]
Thanks Sam,

When I'm trying the example, it seems there are still some errors from samtool, others seems ok.
`Running 'uncalled4 align ref/ec_16s.fa raw/rna002_r9_ec_ivt.fast5 --bam-in mm2/rna002_r9_ec_ivt.bam --bam-out out/rna002_r9_ec_ivt.align.bam 2> out/rna002_r9_ec_ivt.align.err'
Running 'uncalled4 align ref/ec_16s.fa raw/rna002_r9_ec_native.fast5 --bam-in mm2/rna002_r9_ec_native.bam --bam-out out/rna002_r9_ec_native.align.bam 2> out/rna002_r9_ec_native.align.err'
Running 'uncalled4 align ref/dm_chr1.fa raw/dna_r10_dm_ctl.fast5 --bam-in mm2/dna_r10_dm_ctl.bam --bam-out out/dna_r10_dm_ctl.align.bam 2> out/dna_r10_dm_ctl.align.err'
Running 'uncalled4 align ref/dm_chr1.fa raw/dna_r9_dm_ctl.fast5 --bam-in mm2/dna_r9_dm_ctl.bam --bam-out out/dna_r9_dm_ctl.align.bam 2> out/dna_r9_dm_ctl.align.err'
Running 'uncalled4 align --flowcell FLO-MIN106 --kit SQK-RNA002 ref/ec_16s.fa raw/rna002_r9_ec_ivt.pod5 --bam-in mm2/rna002_r9_ec_ivt.bam --bam-out out/rna002_r9_ec_ivt.pod5.align.bam 2> out/rna002_r9_ec_ivt.pod5.align.err'
Running 'uncalled4 align --flowcell FLO-MIN106 --kit SQK-RNA002 ref/ec_16s.fa raw/rna002_r9_ec_ivt.blow5 --bam-in mm2/rna002_r9_ec_ivt.bam --bam-out out/rna002_r9_ec_ivt.blow5.align.bam 2> out/rna002_r9_ec_ivt.blow5.align.err'
Running 'samtools index out/rna002_r9_ec_ivt.align.bam 2> out/rna002_r9_ec_ivt.align.index.err'
rna002_r9_ec_ivt.align.index: failed with code 127
$ cat out/rna002_r9_ec_ivt.align.index.err
./run.sh: line 20: samtools: command not found
`

And for those command, the error is from normalization part of `read = sp.process_signal(signal, normalize=True)`, when I try `read = sp.process_signal(signal)`, there would be no error, but it seems it is not the right result. The code I run is like 
m = PoreModel("dna_r9.4.1_400bps_6mer") #or "dna_r10.4.1_400bps_9mer", "rna_r9.4.1_70bps_5mer", custom TSV file
c = Config()
c.event_detector = EventDetector.PRMS_450BPS #or EventDetector.PRMS_70BPS
sp = SignalProcessor(m,c)
print("yes")
read = sp.process_signal(signal) #signal should be numpy array/list of un-normalized raw sample values

print(read.events["mean"])    #event current means
print(read.events["stdv"])    #event current stdvs
print(read.events["start"])   #event sample starts
print(read.events["length"])  #event sample lengths
print(read.signal)            #normalized raw signal (using method-of-moments)`

the result is `yes
[]
[]
[]
[]
[547 464 463 ... 488 488 492 492]`

**Comment by skovaka** [comment]
Ah I think I know the issue, try adding this line right before initializing "SignalProcessor": `c.event_detector.max_mean = 4000`

The event detector expects the signal to be approximately picoamp-scaled, so by default max_mean is set to 200, so only events with event.mean <= 200 will be output. The values in your input raw signal are "data acquisition" integers, which will be corrected after normalization, but it conflicts with that default event detector parameter. If you're using the ont_fast5_api to read FAST5s, you can instead get approximately picoamp-scaled signal using the option `get_raw_data(scale=True)`. The scaled values are not very accurate, so normalization is still needed. It's mainly useful to identify major outliers prior to normalization. Apologies that none of this is documented, I hope to make the python interface more user-friendly in the future.

Also, a tip for pasting code/output on multiple lines: try surrounding the code blocks with three "back ticks" (```) above and below the lines of code, that way it won't all be put into one line.

Thanks,
Sam

**Comment by hpy17** [comment]
Thank you very much, it works well now!
