### ISSUE TITLE
BAM_IN file for align module

### ISSUE THREAD

**Issue by denisbeslic** [skovaka/uncalled4#10]
Hi,

I have a question regarding the input file (BAM_IN) for the align command of uncalled4. 

Should I use the unprocessed SAM/BAM file I get from guppy/dorado/buttery-eel via the `--moves_out `command? Or do I need to first convert this SAM file to a fastq file and then perform an alignment via minimap2 so it can used as an input for uncalled4?

Using just the unprocessed BAM file from buttery-eel / guppy gives me following error:
`ValueError: file has no sequences defined (mode='rb') - is it SAM/BAM format? Consider opening with check_sq=False`

Thanks for your help.

**Comment by skovaka** [comment]
It should be an aligned binary BAM file, not SAM. If you didn't specify a reference while basecalling then you will need to convert to FASTQ and realign while preserving tags, as described under the example commands in the [README overview](https://github.com/skovaka/uncalled4?tab=readme-ov-file#overview)
