### ISSUE TITLE
.npz model to text and dwell.mean dwell.stdv definition

### ISSUE THREAD

**Issue by hiruna72** [skovaka/uncalled4#14]
Hello Sam,

I wanted to convert the .npz model files to text as we are interested in dwell times.
I am not sure if I am interpreting the dwell.mean and dwell.stdv columns correct.
What are the units of them?
For example, how should I interpret a dwell.mean value of 1.5?

I could get the following model for `dna_r10.4.1_400bps_9mer`. https://github.com/skovaka/uncalled4/blob/main/src/uncalled4/models/dna_r10.4.1_400bps_9mer.npz
````
#_name	dna_r10.4.1_400bps_9mer
#_k	9
#_shift	3
#_pa_mean	92.56193542480469
#_pa_stdv	23.11051368713379
#_norm_max	5.0
#_sample_rate	4000.0
#_bases_per_sec	450.0
#_reverse	False
#_complement	False
#_flowcell	FLO-MIN114
#_kit	SQK-LSK114
kmer	count	dwell.mean	dwell.stdv	current.mean	current.stdv	current_sd.mean	current_sd.stdv	
AAAAAAAAA	1247	1.5	2.145451545715332	-1.8743672370910645	0.3015575408935547	0.06949716806411743	0.03985295817255974	
AAAAAAAAC	1041	1.5	1.459925889968872	-1.7143723964691162	0.26020416617393494	0.07064499706029892	0.0434943363070488	
AAAAAAAAG	1035	1.5	1.2277071475982666	-1.8259941339492798	0.2457960695028305	0.0706958919763565	0.03502160683274269	
AAAAAAAAT	1080	1.75	1.3124371767044067	-1.7253621816635132	0.3119989335536957	0.07063072919845581	0.05145487189292908	
AAAAAAACA	1109	1.5	1.841192603111267	-1.5056740045547485	0.26294776797294617	0.12591834366321564	0.10256802290678024	
AAAAAAACC	1009	1.5	2.00282883644104	-1.4429274797439575	0.26502108573913574	0.12015772610902786	0.10562587529420853	
AAAAAAACG	1023	1.5	2.209913492202759	-1.4983820915222168	0.313260018825531	0.11312674731016159	0.10646407306194305	
AAAAAAACT	1006	1.5	1.9102627038955688	-1.4201548099517822	0.26186034083366394	0.13069398701190948	0.09155462682247162	
````

Thank you!

Here's the code.
````
def convert_npz_to_tsv(npz_file):
    data = dict(np.load(npz_file))
    column_names = []
    header_names = []
    header_values = []
    for key, value in data.items():
        if value.ndim == 1 and value.shape[0] > 1:
            column_names.append(key)
        else:
            header_names.append(key)
            header_values.append(value)
    for i in range(len(header_names)):
        print("#{}\t{}".format(header_names[i], header_values[i]))
    for name in column_names:
        print("{}\t".format(name), end="")
    print()
    value_size = len(data[column_names[0]])
    for i in range(0, value_size):
        for name in column_names:
            print("{}\t".format(data[name][i]), end="")
        print()
````

**Comment by skovaka** [comment]
Good question! Dwell is measured in milliseconds per nucleotide, and can be computed based on raw sample "length" and sample rate: `dwell = 1000 * length / sample_rate` (https://github.com/skovaka/uncalled4/blob/main/src/uncalled4/tracks.py#L280)

You should use the sample_rate listed in the model file, which I see you found. I still need to add support for the new 5khz sample rate and detect that from the input files. That won't affect alignment, it will just scale the reported time by a constant factor here and in visualizations. It could be better to store raw sample "length" rather than dwell in the future, so it won't depend on sample_rate.

Also, I started writing my own script on the dev branch for model npz to tsv conversion. It doesn't output the global parameters like yours, which is a nice addition, but including it here for reference: https://github.com/skovaka/uncalled4/blob/dev/scripts/model2tsv.py

**Comment by hiruna72** [comment]
Hello @skovaka,

Thanks for the answer.

So the `current.mean` column is converted to pA levels by `pa_mean+pa_stdv*current.mean`
How do you transform the `current.stdv` to pA levels?

**Comment by skovaka** [comment]
Correct, that is how you convert the mean values. You can convert the standard deviations by just multiplying by the pA standard deviation: `pa_stdv*current.stdv`

I'm planning to add an option to automatically scale everything to picoamps, I just want to be careful that it doesn't break anything or create inconsistencies. It will likely be in the form of a `--scale-pa` flag for visualizations or when using TSV output.

**Comment by hiruna72** [comment]
Thank you again!

**Comment by hiruna72** [comment]
Hey, 
sorry to bother again. 
I thought it is better to clarify the definitions of `current.mean, current.stdv, current_sd.mean, current_sd.stdv` as well.

This is what I think. Please correct me if I am wrong.

Consider two signals (r0,r1) and a 9-mer (K) we are interested in.
r0 has K in two places.
two events - a and b with lengths n and m respectively.
`a = (a0,a1,...an) -> a0,a1,...,an are raw signal samples.`
`b = (b0,b1,...bm)`
r1 has K in one place. 
an event c with a length p.
`c = (c0,c1,...cp)`

````

current.mean = mean(a,b,c) = mean(a0,...an,b0,...bm,c0,...cp)
current.stdv = stdv(a,b,c) = stdv(a0,...an,b0,...bm,c0,...cp)
current_sd.mean = mean(stdv(a),stdv(b),stdv(c)) = mean(stdv(a0,..an),stdv(b0,..bm),stdv(c0,...cp))
current_sd.stdv = stdv(stdv(a),stdv(b),stdv(c)) = mean(stdv(a0,..an),stdv(b0,..bm),stdv(c0,...cp))

````

**Comment by skovaka** [comment]
Another good question! You have the right idea, but `current.mean` and `current.stdv` are slightly off, they actually mirror your `current_sd` equations:

```
current.mean = mean(mean(a),mean(b),mean(c))
current.stdv = stdv(mean(a),mean(b),mean(c))
```

Also note that a,b, and c refer to per-reference-position values, which could include samples from multiple events aligned to the same position. We are averaging the normalized raw samples contained within the aligned events, not the event means/stdvs. Thanks for checking, I will expand on these methods in the paper revision!

**Comment by hiruna72** [comment]
Thank you Sam. That was very helpful.
