### ISSUE TITLE
guppy is so slow

### ISSUE THREAD

**Issue by abhhba** [skovaka/uncalled4#21]
When I use guppy to basecall fast5 files with the --align-ref option selected, the required time increases by several hundred times. My fast5 files are approximately 100GB each. Is this normal? If it is, then preprocessing a single 100GB fast5 file would take several months to complete.

**Comment by skovaka** [comment]
I have not noticed this, although I haven't performed a direct comparison. Are you using a GPU? You could try running with `--bam_out` instead, which will output unaligned BAM files that you can convert via `samtools fastq -T "mv,ts,pi,sp,ns"...` and align using `minimap2 -y...`  (see [README overview](https://github.com/skovaka/uncalled4?tab=readme-ov-file#overview)). You could also try Dorado, which might be maintained better than Guppy now

**Comment by abhhba** [comment]
Thank you very much for your explanation. I have used Dorado, and it has significantly improved the speed. Now I can generate BAM files with the MV tag correctly.
