### ISSUE TITLE
Warning failed to load read

### ISSUE THREAD

**Issue by iremtll** [skovaka/uncalled4#22]
Hello,

Many thanks for your previous help for the error on new flow cells. I changed to dev-branch but now I encounter an error when I try to run uncalled4 align like that:

`uncalled4 align /UCSC_GRCm38/refMrna.fa /pod5files/ --bam-in /merged.bam --eventalign-out events.tsv -p 10 --eventalign-flags "print-read-names","samples"
`

Error code:

```
Auto-detected flowcell='FLO-PRO004RA' kit='SQK-RNA004'
Warning failed to load read 761aa59e-e742-4a6f-8c23-eaa95e02abde:
KeyError('761aa59e-e742-4a6f-8c23-eaa95e02abde')
Warning failed to load read 48d317bf-cf15-46a6-a02e-2d6a682aa5be:
KeyError('48d317bf-cf15-46a6-a02e-2d6a682aa5be')
```

The only output I get are the following core files:
<img width="560" alt="image" src="https://github.com/skovaka/uncalled4/assets/93679948/883e05b3-b529-4755-9a3a-647b7baf4875">

What could be the reason for that?

Many thanks in advance for your help!

**Comment by iremtll** [comment]
@skovaka thank you for your fast response! 

I've excluded -p 10 and pulled the new dev branch. Now I got the following error:

```
Loading read index '/omics/odcf/analysis/OE0483_projects/nanopath/Irem/Uncalled4/pod5ctr/read_index.txt'
Auto-detected flowcell='FLO-PRO004RA' kit='SQK-RNA004'
Using model 'rna004_130bps_9mer'
/opt/lsf-shared/lsbatch/i420u/1716586608.26900469: line 8: 85911 Segmentation fault      (core dumped) 
```

I checked some of the reads and could see them in the summary file that I created with `pod5 view /pod5files/*.pod5 --output summary.tsv`

`grep '1be1b759-810f-4392-8d25-407faefecf53' summary.tsv `

`1be1b759-810f-4392-8d25-407faefecf53    PAU09113_pass_ba64b2a3_8441b0aa_101.pod5        15991   476     2       signal_positive 18722.68650000        74890746        26.27400000     105096  2633    4000    212.69799805    NaN     NaN     NaN     NaN     0       18748.96093750        ba64b2a3-734a-4e3d-abee-9944216e8d5b    1176465 39118   PAU09113        not_set`

I unfortunately can't send the whole content of pod5files directory since it's confidential but I would be happy to share some example lines&header if it would be enough for you to see the problem.

**Comment by iremtll** [comment]
@skovaka thank you for your answer!

1. it generates only 1 core. file each time. I can email this core file to you.
<img width="642" alt="image" src="https://github.com/skovaka/uncalled4/assets/93679948/be4c63a4-9055-4cc3-a797-7f24ffafae22">

2. Both `--tsv-out `and` --bam-out ` work perfectly. Only `--eventalign-out` doesn't work.

3. I checked the **mv:** and **ts:** tags as follows, and the results were the same.
`samtools view merged.bam | awk '{ if ($0 ~ /ts:/) { print $0 } }' | wc -l`
`samtools view merged.bam | awk '{ if ($0 ~ /mv:/) { print $0 } }' | wc -l`
`samtools view -c merged.bam`

4. Example script runs without any errors.

**Comment by skovaka** [comment]
I think I found the issue! The RNA004 model presently only includes current means, not standard deviations. Uncalled4 doesn't require them by default, but eventalign needs it for the "model_stdv" column. I just pushed an update to the dev branch which fills that column with "inf" when missing. I also considered filling the "0"s instead, and may switch if anybody has a problem with "inf"

I've made quite a few changes on the dev branch recently, unrelated to this issue. I don't think any should functionally affect you, but I can't guarantee it. Let me know if you have any issues, and thanks for helping me work out the bugs!

**Comment by skovaka** [comment]
Just to make sure you have a totally new installation, you should run `pip uninstall uncalled4` then `pip install .`. If you installed with `pip install -e .` at any point then it may not re-compile the C++ code that I made changes to

Unfortunately I can't interpret your core file since we don't have the same OS and python versions. If you have "gdb" installed you could try starting your command with `gdb -ex run -ex bt -ex quit --args python -m uncalled4 align ...`. Python debugging may require some additional setup, but you can try that command to see if it works

**Comment by iremtll** [comment]
@skovaka Thank you! I reinstalled uncalled4 using your new instructions, and the core dump error is resolved. However, I now receive a warning: 'failed to load error. and an empty output tsv file. 

Before `--bam-out` and `--tsv-out` worked but right now they also don't work, even though I'm using the same files.

```
Warning failed to load read 0b03e2a4-7725-4b33-b737-1467ca9cdc25:
KeyError('PAU09113_pass_ba64b2a3_8441b0aa_100.pod5')
Warning failed to load read 5e336b05-9aaf-46de-9c75-a8367597b48b:
RuntimeError('ArrowTableHandle has been closed!')
```

I'm trying gdb now and will update you when I'll manage to run it.

**Comment by skovaka** [comment]
I think this error was related to changes I made to POD5 parsing, which I think I've fixed and just pushed to the dev branch. If you have any similar issues you could try converting your POD5 files to FAST5 or [BLOW5](https://github.com/Psy-Fer/blue-crab), which are currently a bit more reliable with Uncalled4 than POD5. 

Thanks for testing this, and please let me know if you have any more issues! I want to merge these changes into the main branch soon, once I'm more sure that everything is working smoothly

**Comment by iremtll** [comment]
@skovaka it's working now without errors. Thank you very much for all your work! :)
