### ISSUE TITLE
Clarification on 10.4.1 model

### ISSUE THREAD

**Issue by cnk113** [skovaka/uncalled4#29]
Hi Sam,

I'm using the 10.4.1 model and I wanted to double check if it was trained on the 5khz data from the new kits?
Or do you expect there isn't going to be much of a difference from the 4khz and 5khz sampling rate?

Thanks,
Chang

**Comment by skovaka** [comment]
I have run on r10 5khz data and Uncalled4 seems to perform well. I have _not_ trained a specific 5khz model, but I would expect the pore model to be nearly identical. I have trained 4khz 260bps and 400bps k-mer models, the the variability between them is less than between Uncalled4 and ONT r10.4 models, so wouldn't expect a higher sampling rate to affect the pore model much either. It's possible that event detection could be slightly optimized for 5khz, but I doubt it would make much difference and I don't plan on making any changes to that in the near future.
